version: '3.9'

services:
  mysqldb:
    image: mysql:5.7
    env_file:
      - ./.env
    container_name: at-tempo-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - "at-tempo-vol:/var/lib/mysql"

  at-tempo:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build:
      context: .
    container_name: at-tempo-dev
    restart: always
    env_file:
      - ./.env
    environment:
      DB_HOST: mysqldb
      DB_PORT: $DB_PORT
      DB_TYPE: $DB_TYPE
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    volumes:
      - ./:/at-tempo-app
    ports:
      - "3000:3000"
volumes:
  at-tempo-vol: